#!/usr/bin/perl
use strict;
use Cwd qw(cwd);

my $gerrit_git_url = "ssh://git.amd.com:29418";
my $remote_name = "gerrit";

my @dirs = ("."
          , "clang"
          , "compiler"
          , "lld");

my @gerrit_repos = ("lightning/ec/hcc.git"
                  , "compute/ec/hcc-tot/clang.git"
                  , "compute/ec/hcc-tot/llvm.git"
                  , "compute/ec/hcc-tot/lld.git");

my $pwd = cwd;

for(my $i = 0; $i < @dirs; $i++) {
  chdir($dirs[$i]);

  my $git_command = "git remote add $remote_name $gerrit_git_url/$gerrit_repos[$i]";
  #print "$git_command \n";
  system($git_command);

  system("git fetch $remote_name");

  chdir($pwd);
}

