#!/usr/bin/perl
use strict;
use Cwd qw(cwd);

my $gerrit_git_url = "ssh://git.amd.com:29418";
my $gerrit_remote_name = "gerrit";
my $gerrit_legacy_remote_name = "gerrit_legacy";

my $scchan_github_url = "git\@github.com:scchan";
my $scchan_remote_name = "scchan";

my @dirs = ("."
            , "llvm-project");

my @gerrit_repos = ("lightning/ec/hcc.git"
                  , "lightning/ec/llvm-project.git");

my @scchan_repos = ("hcc.git"
                  , "llvm-project.git");

my $pwd = cwd;

for(my $i = 0; $i < @dirs; $i++) {
  chdir($dirs[$i]);

  my $git_command = "git remote add $gerrit_remote_name $gerrit_git_url/$gerrit_repos[$i]";
  #print "$git_command \n";
  system($git_command);
  system("git fetch $gerrit_remote_name");

#  my $git_command = "git remote add $gerrit_legacy_remote_name $gerrit_git_url/$gerrit_legacy_repos[$i]";
  #print "$git_command \n";
#  system($git_command);
#  system("git fetch $gerrit_legacy_remote_name");

  my $git_command = "git remote add $scchan_remote_name $scchan_github_url/$scchan_repos[$i]";
  #print "$git_command \n";
  system($git_command);
  system("git fetch $scchan_remote_name");

  chdir($pwd);
}

