#!/bin/bash

HIP_URL="ssh://scchan@git.amd.com:29418/compute/ec/hip.git"
HIP_BRANCH=amd-develop

git clone -b $HIP_BRANCH $HIP_URL 

HIP_EXAMPLES_URL="ssh://scchan@git.amd.com:29418/compute/ec/hip-examples.git"
HIP_EXAMPLES_BRANCH=amd-master

git clone -b $HIP_EXAMPLES_BRANCH $HIP_EXAMPLES_URL 
