#!/bin/bash

if [ "$#" != "3" ]; then
  echo "Usage: run_amp-conformance_test_one <hcc build dir> <hcc source dir> <test>" 
  exit 1 
fi

COMMAND="perl $1/amp-conformance/test_one.pl $2/amp-conformance/ $2/amp-conformance/$3"
echo $COMMAND
$COMMAND
