#!/bin/bash

ITER=100

# MLOpenConvUni3x32x32x5x5x32x32x32x100xNCHWxFP32x1
./driver/MLOpenDriver conv -F 1 -s 0 -V 1 -t 1 -i $ITER -W 32 -H 32 -c 3 -n 100 -k 32 -x 5 -y 5 -p 2 -q 2 -u 1 -v 1

# MLOpenConvUni32x16x16x5x5x32x16x16x100xNCHWxFP32x1
./driver/MLOpenDriver conv -F 1 -s 0 -V 1 -t 1 -i $ITER -W 16 -H 16 -c 32 -n 100 -k 32 -x 5 -y 5 -p 2 -q 2 -u 1 -v 1

# MLOpenConvUni32x8x8x5x5x64x8x8x100xNCHWxFP32x1
./driver/MLOpenDriver conv -F 1 -s 0 -V 1 -t 1 -i $ITER -W 8 -H 8 -c 32 -n 100 -k 64 -x 5 -y 5 -p 2 -q 2 -u 1 -v 1
