#!/bin/bash


if [[ "$#" != 2 ]]; then
  echo "Usage: docker-nc <image_name> <container_name>"
  exit
fi

IMAGE=$1
CONTAINER=$2

DNS_SERVER1="172.24.3.136"
DNS_SERVER2="172.24.3.137"

docker run --privileged --shm-size="1g" -tid --dns=$DNS_SERVER1 --dns=$DNS_SERVER2 --expose 22 -P --name $CONTAINER  $IMAGE
docker-sshd.ubuntu $CONTAINER
docker port $CONTAINER


