#!/bin/bash


if [[ "$#" != 2 ]]; then
  echo "Usage: docker-nc <image_name> <container_name>"
  exit
fi

IMAGE=$1
CONTAINER=$2

docker run --privileged --shm-size="1g" -tid --expose 22 -P --name $CONTAINER  $IMAGE
docker-sshd.ubuntu $CONTAINER
docker port $CONTAINER


