#!/bin/bash

SYNCLIENT=/usr/bin/synclient
$SYNCLIENT -l | /bin/grep --quiet TouchpadOff.*1


if [ $? -eq 0 ]; then
  #echo "Touchpad is off"
  STATE=0
else
  #echo "Touchpad is on"
  STATE=1
fi

$SYNCLIENT TouchpadOff=$STATE

